# install: conda env create -f ba_package_dev.yaml
# update: conda env update -f ba_package_dev.yaml --prune

name: ba_pipeline_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - setuptools
  - pip
  - ipykernel
  - nb_conda
  - pydantic
  - ffmpeg
  - numpy
  - pandas
  - scipy
  - pyarrow
  - opencv
  - matplotlib
  - seaborn
  - scikit-learn
  - imbalanced-learn
  - natsort
  - tqdm
  - cudatoolkit
  - cudnn
  # dev packages
  - black
  - pytest
  - mkdocs-material
  - mkdocstrings-python
  - pip:
      - -e "../ba_core/"
      - -e "."
