# install: conda env create -f conda_env.yaml
# update: conda env update -f conda_env.yaml --prune

name: ba_pipeline_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - ipykernel
  - nb_conda
  - ffmpeg
  # GPU packages (for deeplabcut) # TODO: move to dlc_subproc_wrapper
  # - cudatoolkit
  # - cudnn
