[tool.poetry]
name = "ba_pipeline"
version = "0.1.0"
description = "A behaviour processing and analysis package"
authors = ["BowenLab"]
license = "LGPL-3.0-or-later"
readme = "README.md"
packages = [{ include = "ba_pipeline" }]

[tool.poetry.dependencies]
python = "^3.9"
seaborn = "^0.13.2"
scikit-learn = "^1.4.2"
imbalanced-learn = "^0.12.2"

# deeplabcut = { extras = ["tf"], version = "^2.3.9" }
# ba_core = "^0.1.0"
ba_core = { path = "../ba_core", develop = true }

[tool.poetry.group.dev.dependencies]
black = "^24.4.0"
pytest = "^8.1.1"
mkdocs-material = "^9.5.18"
mkdocstrings-python = "^1.9.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
