[tool.poetry]
name = "behavysis_pipeline"
version = "0.1.2"
description = "An animal behaviour processing and analysis package"
authors = ["BowenLab"]
license = "LGPL-3.0-or-later"
readme = "README.md"
packages = [{ include = "behavysis_pipeline" }]

[tool.poetry.dependencies]
python = "^3.9"
seaborn = "^0.13.2"
scikit-learn = "^1.4.2"
imbalanced-learn = "^0.12.2"
Jinja2 = "^3.1.4"
behavysis_core = "^0.1.3"
torch = {version = "==2.3.1+cu121", source = "torch"}
torchvision = {version = "==0.18.1+cu121", source = "torch"}
torchaudio = {version = "==2.3.1+cu121", source = "torch"}

[tool.poetry.group.dev.dependencies]
behavysis_core = { path = "../behavysis_core", develop = true }
ruff = "^0.4.8"
mkdocs-material = "^9.5.18"
mkdocstrings-python = "^1.9.2"

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
